### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'AppLimit.NetSparkle

### ISSUE THREAD

**Issue by lamathe** [Deadpikle/NetSparkle#75]
Our WPF App (x86) has been encountering an error multiple times with FileNotFoundException for AppLimit.NetSparkle even though the DLL being present.

System.IO.FileNotFoundException: Could not load file or assembly 'AppLimit.NetSparkle, Version=1.0.84.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at BibaApplication.Managers.BibaUpgradeManager.<>c__DisplayClass8_0.<EnsureSparkleUpdatedAsync>b__0()
   at BibaApplication.Managers.BibaUpgradeManager.<QueryEarlyAdoptersFeatureAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

If there is any pointer to get around this.

**Comment by Deadpikle** [comment]
Hi @lamathe!

Hm. The version # referenced in your callstack is wrong. How are you referencing NetSparkle in your project? Are you using Nuget? Are you referencing the `NetSparkle` Nuget or `NetSparkle.New`? Do you have two NetSparkle references in your code somehow? Can you please provide more details on your setup?

Thanks! :)

**Comment by Deadpikle** [comment]
Wait, what is `AppLimit.NetSparkle`? Is `AppLimit` another library you're referencing? (Sorry I didn't notice that before.)

**Comment by Deadpikle** [comment]
@lamathe 

I see that `AppLimit.NetSparkle` is the old namespace for this project. (It's been so long since that was changed that I forgot!) This means you are not using this fork of the code. Please reopen this issue if you choose to use this fork. Please also keep in mind, for whatever project you're working on right now, that the old version under the `AppLimit.NetSparkle` namespace is _not_ updated anymore by dei79 or others. This fork is the latest NetSparkle code that I know of, and I am working towards a 2.0 version right now. (The current version numbers are < 1.0 right now for other reasons.)

In the meantime, here is an SO post you may find helpful: https://stackoverflow.com/questions/8369408/c-sharp-app-cant-find-dll-in-its-working-directory

Thanks!

**Comment by lamathe** [comment]
Cool thanks @Deadpikle
